name: Node.js Express CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build and start Express app
    run: |
      npm run build
      npm start &
      sleep 10 # Wait for server to start

    - name: Wait for server to start
      run: sleep 10

    - name: Run Postman tests
      run: |
        npm install -g newman
        newman run test-collection.json